name: Check Provider URLs

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run URL checker
        run: go run .github/scripts/url-checker.go

      - name: Commit changes if any
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add providers.json

          if [[ $(git status --porcelain providers.json) ]]; then
            echo "Found changes in providers.json, committing..."
            git commit -m "Update provider URLs [skip ci]"
            git push
          else
            echo "No changes detected in providers.json"
          fi
